export const ADD_ERROR = "ADD_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

/* *****Chat Actions***** */
export const NEW_MESSAGE = "NEW_MESSAGE";
export const CHANGE_SELECTED_CHANNEL = "CHANGE_SELECTED_CHANNEL";
export const CHANGE_CONVERSATION = "CHANGE_COVERSATION";